// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartBiodiversityUtn.Data;

#nullable disable

namespace SmartBiodiversityUtn.Migrations
{
    [DbContext(typeof(SmartBiodiversityUtnContext))]
    [Migration("20260719135635_ActualizarEsquemaAportes")]
    partial class ActualizarEsquemaAportes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Aporte", b =>
                {
                    b.Property<string>("IdAporte")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DescripcionApo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EstadoApo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAprobacionApo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionApo")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuarioApo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RutaArchivoApo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TituloApo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdAporte");

                    b.HasIndex("IdUsuarioApo");

                    b.ToTable("Aportes");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Aviso", b =>
                {
                    b.Property<string>("IdAvisos")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ActivoAvi")
                        .HasColumnType("bit");

                    b.Property<string>("CategoriaAvi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaFinAvi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIniAvi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdRolesAvi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MensajeAvi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TituloAvi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdAvisos");

                    b.HasIndex("IdRolesAvi");

                    b.ToTable("Avisos");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Bitacora", b =>
                {
                    b.Property<string>("IdLog")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccionBit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DetalleBit")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaBit")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdRolesBit")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdUsuarioBit")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdLog");

                    b.HasIndex("IdRolesBit");

                    b.HasIndex("IdUsuarioBit");

                    b.ToTable("Bitacora");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Categoria", b =>
                {
                    b.Property<string>("IdCategorias")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreCat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategorias");

                    b.HasIndex("NombreCat")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Especie", b =>
                {
                    b.Property<string>("IdEspecies")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DescripcionEsp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstadoEsp")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistroEsp")
                        .HasColumnType("datetime2");

                    b.Property<string>("HabitatEsp")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IdCategoriaEsp")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreCientificoEsp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreComunEsp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEspecies");

                    b.HasIndex("IdCategoriaEsp");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.HistorialContrasena", b =>
                {
                    b.Property<string>("IdHistorialHco")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaHco")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuarioHco")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHashHco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdHistorialHco");

                    b.HasIndex("IdUsuarioHco");

                    b.ToTable("HistorialContra");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Multimedia", b =>
                {
                    b.Property<string>("IdMultimedia")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaMul")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdEspeciesMul")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RutaArchivoMul")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoArchivoMul")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMultimedia");

                    b.HasIndex("IdEspeciesMul");

                    b.ToTable("Multimedia");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Rol", b =>
                {
                    b.Property<string>("IdRoles")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRoles");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Token", b =>
                {
                    b.Property<string>("IdTokens")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodigoTok")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacionTok")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracionTok")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuarioTok")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TipoTok")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Usado")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdTokens");

                    b.HasIndex("CodigoTok")
                        .IsUnique();

                    b.HasIndex("IdUsuarioTok");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Usuario", b =>
                {
                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("BloqueoHasta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdRolesU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdRolesU");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Aporte", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Usuario", "Usuario")
                        .WithMany("Aportes")
                        .HasForeignKey("IdUsuarioApo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Aviso", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Rol", "Rol")
                        .WithMany("Avisos")
                        .HasForeignKey("IdRolesAvi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Bitacora", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Rol", "Rol")
                        .WithMany("Bitacoras")
                        .HasForeignKey("IdRolesBit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBiodiversityUtnModels.Entities.Usuario", "Usuario")
                        .WithMany("Bitacoras")
                        .HasForeignKey("IdUsuarioBit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Especie", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Categoria", "Categoria")
                        .WithMany("Especies")
                        .HasForeignKey("IdCategoriaEsp")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.HistorialContrasena", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Usuario", "Usuario")
                        .WithMany("HistorialContrasenas")
                        .HasForeignKey("IdUsuarioHco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Multimedia", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Especie", "Especie")
                        .WithMany("MultimediaArchivos")
                        .HasForeignKey("IdEspeciesMul")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Token", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Usuario", "Usuario")
                        .WithMany("Tokens")
                        .HasForeignKey("IdUsuarioTok")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Usuario", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRolesU")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Categoria", b =>
                {
                    b.Navigation("Especies");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Especie", b =>
                {
                    b.Navigation("MultimediaArchivos");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Rol", b =>
                {
                    b.Navigation("Avisos");

                    b.Navigation("Bitacoras");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Usuario", b =>
                {
                    b.Navigation("Aportes");

                    b.Navigation("Bitacoras");

                    b.Navigation("HistorialContrasenas");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
