// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartBiodiversityUtn.Data;

#nullable disable

namespace SmartBiodiversityUtn.Migrations
{
    [DbContext(typeof(SmartBiodiversityUtnContext))]
    [Migration("20260723143104_NUevasEntidades")]
    partial class NUevasEntidades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Aporte", b =>
                {
                    b.Property<string>("IdAporte")
                        .HasColumnType("text");

                    b.Property<string>("DescripcionApo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EstadoApo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaAprobacionApo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacionApo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdUsuarioApo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RutaArchivoApo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TituloApo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdAporte");

                    b.HasIndex("IdUsuarioApo");

                    b.ToTable("Aportes");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Aviso", b =>
                {
                    b.Property<string>("IdAvisos")
                        .HasColumnType("text");

                    b.Property<bool>("ActivoAvi")
                        .HasColumnType("boolean");

                    b.Property<string>("CategoriaAvi")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaFinAvi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaIniAvi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdRolesAvi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MensajeAvi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TituloAvi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdAvisos");

                    b.HasIndex("IdRolesAvi");

                    b.ToTable("Avisos");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Bitacora", b =>
                {
                    b.Property<string>("IdLog")
                        .HasColumnType("text");

                    b.Property<string>("AccionBit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DetalleBit")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("FechaBit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdRolesBit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdUsuarioBit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdLog");

                    b.HasIndex("IdRolesBit");

                    b.HasIndex("IdUsuarioBit");

                    b.ToTable("Bitacora");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Categoria", b =>
                {
                    b.Property<string>("IdCategorias")
                        .HasColumnType("text");

                    b.Property<string>("NombreCat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdCategorias");

                    b.HasIndex("NombreCat")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.DetalleFauna", b =>
                {
                    b.Property<string>("IdEspecies")
                        .HasColumnType("text");

                    b.Property<string>("Dieta")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DimorfismoSexual")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal?>("EnvergaduraCm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("LongitudPromedioCm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("PatronActividad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("PesoPromedioGramos")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("TipoPelajePlumaje")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdEspecies");

                    b.ToTable("DetallesFauna");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.DetalleFlora", b =>
                {
                    b.Property<string>("IdEspecies")
                        .HasColumnType("text");

                    b.Property<decimal?>("AlturaMaximaM")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("AlturaPromedioM")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ColorFlorFruto")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("DiametroTroncoCm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("FormaCopa")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HabitoCrecimiento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoCortezaTronco")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TipoHoja")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("IdEspecies");

                    b.ToTable("DetallesFlora");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Especie", b =>
                {
                    b.Property<string>("IdEspecies")
                        .HasColumnType("text");

                    b.Property<string>("DescripcionEsp")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("EstadoEsp")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRegistroEsp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HabitatEsp")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IdCategoriaEsp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreCientificoEsp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreComunEsp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdEspecies");

                    b.HasIndex("IdCategoriaEsp");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.EspecieFacultad", b =>
                {
                    b.Property<string>("IdEspecieFacultad")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdEspecies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdFacultad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEspecieFacultad");

                    b.HasIndex("IdFacultad");

                    b.HasIndex("IdEspecies", "IdFacultad")
                        .IsUnique();

                    b.ToTable("EspecieFacultad");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Facultad", b =>
                {
                    b.Property<string>("IdFacultad")
                        .HasColumnType("text");

                    b.Property<string>("DescripcionFac")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("NombreFac")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("NumeroFac")
                        .HasColumnType("integer");

                    b.HasKey("IdFacultad");

                    b.HasIndex("NombreFac")
                        .IsUnique();

                    b.ToTable("Facultades");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.HistorialContrasena", b =>
                {
                    b.Property<string>("IdHistorialHco")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHco")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdUsuarioHco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHashHco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdHistorialHco");

                    b.HasIndex("IdUsuarioHco");

                    b.ToTable("HistorialContra");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Multimedia", b =>
                {
                    b.Property<string>("IdMultimedia")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaMul")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdEspeciesMul")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RutaArchivoMul")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TipoArchivoMul")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdMultimedia");

                    b.HasIndex("IdEspeciesMul");

                    b.ToTable("Multimedia");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Rol", b =>
                {
                    b.Property<string>("IdRoles")
                        .HasColumnType("text");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdRoles");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Token", b =>
                {
                    b.Property<string>("IdTokens")
                        .HasColumnType("text");

                    b.Property<string>("CodigoTok")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CorreoTok")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaCreacionTok")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaExpiracionTok")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdUsuarioTok")
                        .HasColumnType("text");

                    b.Property<string>("TipoTok")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Usado")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("IdTokens");

                    b.HasIndex("CodigoTok");

                    b.HasIndex("CorreoTok");

                    b.HasIndex("IdUsuarioTok");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Usuario", b =>
                {
                    b.Property<string>("IdUsuario")
                        .HasColumnType("text");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("BloqueoHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdRolesU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdRolesU");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Aporte", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Usuario", "Usuario")
                        .WithMany("Aportes")
                        .HasForeignKey("IdUsuarioApo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Aviso", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Rol", "Rol")
                        .WithMany("Avisos")
                        .HasForeignKey("IdRolesAvi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Bitacora", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Rol", "Rol")
                        .WithMany("Bitacoras")
                        .HasForeignKey("IdRolesBit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBiodiversityUtnModels.Entities.Usuario", "Usuario")
                        .WithMany("Bitacoras")
                        .HasForeignKey("IdUsuarioBit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.DetalleFauna", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Especie", "Especie")
                        .WithOne("DetalleFauna")
                        .HasForeignKey("SmartBiodiversityUtnModels.Entities.DetalleFauna", "IdEspecies")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.DetalleFlora", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Especie", "Especie")
                        .WithOne("DetalleFlora")
                        .HasForeignKey("SmartBiodiversityUtnModels.Entities.DetalleFlora", "IdEspecies")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Especie", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Categoria", "Categoria")
                        .WithMany("Especies")
                        .HasForeignKey("IdCategoriaEsp")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.EspecieFacultad", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Especie", "Especie")
                        .WithMany("EspecieFacultades")
                        .HasForeignKey("IdEspecies")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBiodiversityUtnModels.Entities.Facultad", "Facultad")
                        .WithMany("EspecieFacultades")
                        .HasForeignKey("IdFacultad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.HistorialContrasena", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Usuario", "Usuario")
                        .WithMany("HistorialContrasenas")
                        .HasForeignKey("IdUsuarioHco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Multimedia", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Especie", "Especie")
                        .WithMany("MultimediaArchivos")
                        .HasForeignKey("IdEspeciesMul")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Token", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Usuario", "Usuario")
                        .WithMany("Tokens")
                        .HasForeignKey("IdUsuarioTok")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Usuario", b =>
                {
                    b.HasOne("SmartBiodiversityUtnModels.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRolesU")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Categoria", b =>
                {
                    b.Navigation("Especies");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Especie", b =>
                {
                    b.Navigation("DetalleFauna");

                    b.Navigation("DetalleFlora");

                    b.Navigation("EspecieFacultades");

                    b.Navigation("MultimediaArchivos");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Facultad", b =>
                {
                    b.Navigation("EspecieFacultades");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Rol", b =>
                {
                    b.Navigation("Avisos");

                    b.Navigation("Bitacoras");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SmartBiodiversityUtnModels.Entities.Usuario", b =>
                {
                    b.Navigation("Aportes");

                    b.Navigation("Bitacoras");

                    b.Navigation("HistorialContrasenas");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
